### ISSUE TITLE
Retrieve editor contents/Expose quill instance

### ISSUE THREAD

**Issue by mattcreaser** [goinstant/rich-text-editor#9]
Doesn't look like there's a publicly exposed method for retrieve the editor contents programatically.

Since the widget is built on top of Quill, which does expose this functionality, perhaps the internal Quill instance should just be exposed publicly and documented?

Alternatively there could be interfaces that call through to the Quill instance if you don't want to expose that for encapsulation reasons.

**Comment by byronm** [comment]
Good point.

I think that since the idea behind the widget is simplicity and drop-in functionality, we should maintain encapsulation around Quill. 

For the purpose of retrieving editor contents, it may make more sense to expose a reference (or wrapper interface) to the GoInstant OT api, rather than to Quill, since OT is the data layer. 

One option would be to add a `documentName` option to the widget constructor, so that you can specify the OT key that gets created/loaded (if it doesn't already exist). This make the widget capable of supporting multiple documents within the same room, which seems like a good thing.

Then the only decision would be if we want to rely on the client instantiating their own OT key (using `documentName`), return a reference to the OT key via a call into the widget, or just return the contents via a call into the widget.

What do you think?
